# Generated by Django 4.1.7 on 2023-02-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='diploma',
        ),
        migrations.RemoveField(
            model_name='school',
            name='nb_years',
        ),
        migrations.RemoveField(
            model_name='student',
            name='already_graduated',
        ),
    ]
