# Generated by Django 4.1.7 on 2023-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_school_diploma_remove_school_nb_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='already_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
