# Generated by Django 4.1.7 on 2023-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_already_graduated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='already_graduated',
        ),
        migrations.AddField(
            model_name='student',
            name='already_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
